2014-01-08T09:38:06.215073+00:00 app[web.1]: 2014-01-08 09:38:06 [2] [INFO] Using worker: sync
2014-01-08T09:38:06.214355+00:00 app[web.1]: 2014-01-08 09:38:06 [2] [INFO] Starting gunicorn 18.0
2014-01-08T09:38:06.214999+00:00 app[web.1]: 2014-01-08 09:38:06 [2] [INFO] Listening at: http://0.0.0.0:34589 (2)
2014-01-08T09:38:06.241159+00:00 app[web.1]: 2014-01-08 09:38:06 [7] [INFO] Booting worker with pid: 7
2014-01-08T09:38:06.686349+00:00 heroku[web.1]: State changed from starting to up
2014-01-08T09:38:07.139735+00:00 app[web.1]: 2014-01-08 09:38:07 [7] [ERROR] Exception in worker process:
2014-01-08T09:38:07.139735+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T09:38:07.139735+00:00 app[web.1]:     worker.init_process()
2014-01-08T09:38:07.139735+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T09:38:07.139735+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T09:38:07.139735+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T09:38:07.139735+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T09:38:07.139735+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T09:38:07.139735+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T09:38:07.139735+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T09:38:07.139956+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T09:38:07.139956+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T09:38:07.139956+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T09:38:07.139956+00:00 app[web.1]:     __import__(module)
2014-01-08T09:38:07.139956+00:00 app[web.1]:   File "/app/rosterrun.py", line 6, in <module>
2014-01-08T09:38:07.139956+00:00 app[web.1]:     from scheduler import run_scheduler_OAuth, scheduler, testConnectToSpreadsheetsServiceOAuth, Combination, initializeDataOAuth, Character
2014-01-08T09:38:07.140115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T09:38:07.139956+00:00 app[web.1]:   File "/app/scheduler.py", line 337
2014-01-08T09:38:07.139956+00:00 app[web.1]:     combinationsMapping = dict((k, v) for (k, v) in combinationsMapping.iteritems() if v = successfulteam)
2014-01-08T09:38:07.139956+00:00 app[web.1]:                                                                                          ^
2014-01-08T09:38:07.139956+00:00 app[web.1]: SyntaxError: invalid syntax
2014-01-08T09:38:07.140115+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T09:38:07.140115+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T09:38:07.140115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T09:38:07.140115+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T09:38:07.140115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T09:38:07.140115+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T09:38:07.140115+00:00 app[web.1]:     worker.init_process()
2014-01-08T09:38:07.140115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T09:38:07.140115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T09:38:07.140543+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T09:38:07.140543+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T09:38:07.140543+00:00 app[web.1]:   File "/app/rosterrun.py", line 6, in <module>
2014-01-08T09:38:07.140543+00:00 app[web.1]:     from scheduler import run_scheduler_OAuth, scheduler, testConnectToSpreadsheetsServiceOAuth, Combination, initializeDataOAuth, Character
2014-01-08T09:38:07.140543+00:00 app[web.1]:   File "/app/scheduler.py", line 337
2014-01-08T09:38:07.140543+00:00 app[web.1]:     combinationsMapping = dict((k, v) for (k, v) in combinationsMapping.iteritems() if v = successfulteam)
2014-01-08T09:38:07.140543+00:00 app[web.1]:                                                                                          ^
2014-01-08T09:38:07.140543+00:00 app[web.1]: SyntaxError: invalid syntax
2014-01-08T09:38:07.140543+00:00 app[web.1]: 2014-01-08 09:38:07 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T09:38:07.278464+00:00 app[web.1]: 2014-01-08 09:38:07 [2] [INFO] Shutting down: Master
2014-01-08T09:38:07.278590+00:00 app[web.1]: 2014-01-08 09:38:07 [2] [INFO] Reason: Worker failed to boot.
2014-01-08T09:38:07.140543+00:00 app[web.1]:     __import__(module)
2014-01-08T09:38:08.710641+00:00 heroku[web.1]: Process exited with status 3
2014-01-08T09:38:08.728548+00:00 heroku[web.1]: State changed from up to crashed
2014-01-08T09:38:08.729474+00:00 heroku[web.1]: State changed from crashed to starting
2014-01-08T09:38:22.872318+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2014-01-08T09:38:24.651936+00:00 app[web.1]: 2014-01-08 09:38:24 [2] [INFO] Starting gunicorn 18.0
2014-01-08T09:38:24.660873+00:00 app[web.1]: 2014-01-08 09:38:24 [2] [INFO] Listening at: http://0.0.0.0:14216 (2)
2014-01-08T09:38:24.662829+00:00 app[web.1]: 2014-01-08 09:38:24 [2] [INFO] Using worker: sync
2014-01-08T09:38:24.683174+00:00 app[web.1]: 2014-01-08 09:38:24 [7] [INFO] Booting worker with pid: 7
2014-01-08T09:38:24.709581+00:00 heroku[web.1]: State changed from starting to up
2014-01-08T09:38:25.343747+00:00 app[web.1]: 2014-01-08 09:38:25 [7] [ERROR] Exception in worker process:
2014-01-08T09:38:25.343747+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T09:38:25.343747+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T09:38:25.343747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T09:38:25.343747+00:00 app[web.1]:     worker.init_process()
2014-01-08T09:38:25.343747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T09:38:25.343953+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T09:38:25.343953+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T09:38:25.343747+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T09:38:25.343747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T09:38:25.343953+00:00 app[web.1]:   File "/app/scheduler.py", line 337
2014-01-08T09:38:25.343747+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T09:38:25.344137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T09:38:25.343953+00:00 app[web.1]:                                                                                          ^
2014-01-08T09:38:25.343953+00:00 app[web.1]:     from scheduler import run_scheduler_OAuth, scheduler, testConnectToSpreadsheetsServiceOAuth, Combination, initializeDataOAuth, Character
2014-01-08T09:38:25.344137+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T09:38:25.343953+00:00 app[web.1]: SyntaxError: invalid syntax
2014-01-08T09:38:25.344597+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T09:38:25.343747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T09:38:25.344137+00:00 app[web.1]:     worker.init_process()
2014-01-08T09:38:25.343953+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T09:38:25.343953+00:00 app[web.1]:     __import__(module)
2014-01-08T09:38:25.344137+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T09:38:25.344597+00:00 app[web.1]:     combinationsMapping = dict((k, v) for (k, v) in combinationsMapping.iteritems() if v = successfulteam)
2014-01-08T09:38:25.344597+00:00 app[web.1]: SyntaxError: invalid syntax
2014-01-08T09:38:25.344597+00:00 app[web.1]:   File "/app/scheduler.py", line 337
2014-01-08T09:38:25.344597+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T09:38:25.344137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T09:38:25.344137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T09:38:25.343953+00:00 app[web.1]:   File "/app/rosterrun.py", line 6, in <module>
2014-01-08T09:38:25.343953+00:00 app[web.1]:     combinationsMapping = dict((k, v) for (k, v) in combinationsMapping.iteritems() if v = successfulteam)
2014-01-08T09:38:25.344597+00:00 app[web.1]:     from scheduler import run_scheduler_OAu
th, scheduler, testConnectToSpreadsheetsServiceOAuth, Combination, initializeDataOAuth, Character
2014-01-08T09:38:25.344597+00:00 app[web.1]:                                                                                          ^
2014-01-08T09:38:25.344597+00:00 app[web.1]:   File "/app/rosterrun.py", line 6, in <module>
2014-01-08T09:38:25.344137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T09:38:25.344137+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T09:38:25.344597+00:00 app[web.1]: 2014-01-08 09:38:25 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T09:38:25.344137+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T09:38:25.344137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T09:38:25.344597+00:00 app[web.1]:     __import__(module)
2014-01-08T09:38:25.469748+00:00 app[web.1]: 2014-01-08 09:38:25 [2] [INFO] Shutting down: Master
2014-01-08T09:38:25.469748+00:00 app[web.1]: 2014-01-08 09:38:25 [2] [INFO] Reason: Worker failed to boot.
2014-01-08T09:38:26.914971+00:00 heroku[web.1]: Process exited with status 3
2014-01-08T09:38:26.928269+00:00 heroku[web.1]: State changed from up to crashed
2014-01-08T09:38:59.593767+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno= connect= service= status=503 bytes=
Terminate batch job (Y/N)? 

C:\Users\andy\Documents\GitHub\rosterrun>