2014-01-08T11:50:45.266511+00:00 app[web.1]: 2014-01-08 11:50:45 [2] [INFO] Using worker: sync
2014-01-08T11:50:45.273792+00:00 app[web.1]: 2014-01-08 11:50:45 [7] [INFO] Booting worker with pid: 7
2014-01-08T11:50:45.494485+00:00 heroku[web.1]: State changed from starting to up
2014-01-08T11:50:45.902178+00:00 heroku[worker.2]: State changed from starting to up
2014-01-08T11:50:46.395364+00:00 app[worker.2]: 11:50:46 RQ worker started, version 0.3.13
2014-01-08T11:50:46.397038+00:00 app[worker.2]: 11:50:46 
2014-01-08T11:50:46.397121+00:00 app[worker.2]: 11:50:46 *** Listening on high, default, low...
2014-01-08T11:50:47.406266+00:00 app[web.1]: cannot find gdoc name
2014-01-08T11:50:47.406266+00:00 app[web.1]: show entries
2014-01-08T11:50:47.406266+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T11:50:47.553989+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T11:50:47.553989+00:00 app[web.1]: get all combinations
2014-01-08T11:50:47.599419+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=4ms service=252ms status=200 bytes=16659
2014-01-08T11:50:51.784343+00:00 heroku[router]: at=info method=GET path=/login host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=3ms service=11ms status=200 bytes=563
2014-01-08T11:50:51.583121+00:00 heroku[router]: at=info method=GET path=/logout host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=2ms service=13ms status=302 bytes=209
2014-01-08T11:50:51.683702+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=5ms service=12ms status=302 bytes=219
2014-01-08T11:50:55.447475+00:00 app[web.1]: running with user andygee@gmail.com 
2014-01-08T11:50:55.451962+00:00 heroku[router]: at=info method=POST path=/login host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=2ms service=8ms status=302 bytes=803
2014-01-08T11:50:56.532425+00:00 heroku[router]: at=info method=GET path=/auth_return?code=4/--wdPU_M08XXxLZWi4P9iQ9p4c1B.QvfZVuRUGpAWmmS0T3UFEsO4eWXjhgI host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=4ms service=676ms status=302 bytes=209
2014-01-08T11:50:56.649876+00:00 app[web.1]: show entries
2014-01-08T11:50:56.649876+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T11:50:56.649876+00:00 app[web.1]: cannot find gdoc name
2014-01-08T11:50:56.662207+00:00 app[web.1]: get all combinations
2014-01-08T11:50:56.685784+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=40ms status=200 bytes=16708
2014-01-08T11:50:56.662207+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T11:51:01.800308+00:00 app[web.1]: running with user andygee@gmail.com 
2014-01-08T11:51:02.411187+00:00 app[web.1]: trying to find the spreadsheet named Quest Status 
2014-01-08T11:51:02.411187+00:00 app[web.1]: t0r5xf97B-k70k6TxherGcw
2014-01-08T11:51:02.411187+00:00 app[web.1]: ['Quest Status']
2014-01-08T11:51:02.847080+00:00 heroku[router]: at=info method=POST path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=2ms service=1063ms status=500 bytes=135
2014-01-08T11:51:02.848753+00:00 app[web.1]: 2014-01-08 11:51:02 [7] [ERROR] Error handling request
2014-01-08T11:51:02.848753+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2014-01-08T11:51:02.848753+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T11:51:02.848753+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-01-08T11:51:02.848753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-01-08T11:51:02.848753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2014-01-08T11:51:02.848753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2014-01-08T11:51:02.848753+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-01-08T11:51:02.848952+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-01-08T11:51:02.848952+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-01-08T11:51:02.848753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-01-08T11:51:02.848753+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-01-08T11:51:02.848952+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-01-08T11:51:02.848952+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-01-08T11:51:02.848952+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-01-08T11:51:02.848952+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-01-08T11:51:02.848952+00:00 app[web.1]:     rv = self.dispatch_request()
2014-01-08T11:51:02.848952+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-01-08T11:51:02.849124+00:00 app[web.1]:   File "/app/rosterrun.py", line 141, in show_entries
2014-01-08T11:51:02.849124+00:00 app[web.1]:     run_calculation()
2014-01-08T11:51:02.848952+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-01-08T11:51:02.848952+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-01-08T11:51:02.849124+00:00 app[web.1]:     print 'running calc %s ' % job.id
2014-01-08T11:51:02.849124+00:00 app[web.1]:   File "/app/rosterrun.py", line 271, in run_calculation
2014-01-08T11:51:02.849124+00:00 app[web.1]: NameError: global name 'job' is not defined
2014-01-08T11:51:02.921826+00:00 app[worker.1]: 11:51:02 default: scheduler.run_scheduler_OAuth(<oauth2client.client.OAuth2Credentials object at 0x3e4eb90>, u'Quest Status') (cb3d2ac9-142a-4367-84e7-b7389050529b)
2014-01-08T11:51:03.749653+00:00 app[worker.1]: trying to find the spreadsheet named Quest Status 
2014-01-08T11:51:03.749767+00:00 app[worker.1]: ['Quest Status']
2014-01-08T11:51:03.749767+00:00 app[worker.1]: t0r5xf97B-k70k6TxherGcw
2014-01-08T11:52:14.040519+00:00 app[worker.1]: found 156 combinations
2014-01-08T11:52:16.093907+00:00 app[worker.1]: found 1 
2014-01-08T11:52:20.765434+00:00 app[worker.1]: found 36 combinations
2014-01-08T11:52:20.822106+00:00 app[worker.1]: found 1 
2014-01-08T11:52:40.113228+00:00 app[worker.1]: found 152 combinations
2014-01-08T11:52:42.665376+00:00 app[worker.1]: found 2 
2014-01-08T11:52:42.694888+00:00 app[worker.1]: 11:52:42 Job OK, result = [[<scheduler.Combination instance at 0x2d65ea8>, <scheduler.Combination instance at 0x2d65fc8>, <scheduler.Combination instance at 0x2d65e18>, <scheduler.Combination instance at 0x2d65f38>, <scheduler.Combination instance at 0x2d724d0>, <scheduler.Combination instance at 0x2d722d8>, <scheduler.Combination instance at 0x2d72200>], [<scheduler.Combination instance at 0x2d675f0>, <scheduler.Combination instance at 0x2d67f38>, <scheduler.Combination instance at 0x2d67050>, <scheduler.Combination instance at 0x2d671b8>, <scheduler.Combination instance at 0x2d67170>], [<scheduler.Combination instance at 0x2c01560>, <scheduler.Combination instance at 0x2c015a8>, <scheduler.Combination instance at 0x2c015f0>, <scheduler.Combination instance at 0x2c01638>, <scheduler.Combination instance at 0x2c01680>, <scheduler.Combination instance at 0x2c016c8>], [<scheduler.Combination instance at 0x2c01710>, <scheduler.Combination instance at 0x2c01758>, <scheduler.Combination instance at 0x2c017a0>, <s
2014-01-08T11:52:42.694888+00:00 app[worker.1]: cheduler.Combination instance at 0x2c017e8>, <scheduler.Combination instance at 0x2c01830>, <scheduler.Combination instance at 0x2c01878>]]
2014-01-08T11:52:42.694888+00:00 app[worker.1]: 11:52:42 Result is kept for 500 seconds.
2014-01-08T11:52:42.742090+00:00 app[worker.1]: 11:52:42 *** Listening on high, default, low...
2014-01-08T11:52:42.742090+00:00 app[worker.1]: 11:52:42 
2014-01-08T11:53:25+00:00 heroku[slug-compiler]: Slug compilation started
2014-01-08T11:54:27.148503+00:00 heroku[api]: Deploy 3cc17f1 by andygee@gmail.com
2014-01-08T11:54:27.177321+00:00 heroku[api]: Release v136 created by andygee@gmail.com
2014-01-08T11:54:27+00:00 heroku[slug-compiler]: Slug compilation finished
2014-01-08T11:54:28.124071+00:00 heroku[web.1]: State changed from up to starting
2014-01-08T11:54:28.182589+00:00 heroku[worker.2]: State changed from up to starting
2014-01-08T11:54:28.275890+00:00 heroku[worker.1]: State changed from up to starting
2014-01-08T11:54:30.861765+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2014-01-08T11:54:31.005355+00:00 heroku[worker.2]: Stopping all processes with SIGTERM
2014-01-08T11:54:31.346758+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2014-01-08T11:54:31.425470+00:00 app[web.1]: 2014-01-08 11:54:31 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T11:54:31.425739+00:00 app[web.1]: 2014-01-08 11:54:31 [2] [INFO] Handling signal: term
2014-01-08T11:54:31.440766+00:00 app[web.1]: 2014-01-08 11:54:31 [2] [INFO] Shutting down: Master
2014-01-08T11:54:31.587901+00:00 app[worker.2]: 11:54:31 Warm shut down requested.
2014-01-08T11:54:32.118123+00:00 app[worker.1]: 11:54:32 Warm shut down requested.
2014-01-08T11:54:32.686203+00:00 heroku[web.1]: Process exited with status 0
2014-01-08T11:54:33.079448+00:00 heroku[worker.2]: Process exited with status 0
2014-01-08T11:54:33.312587+00:00 heroku[worker.1]: Process exited with status 0
2014-01-08T11:54:37.952736+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2014-01-08T11:54:38.878737+00:00 app[web.1]: 2014-01-08 11:54:38 [2] [INFO] Starting gunicorn 18.0
2014-01-08T11:54:38.879323+00:00 app[web.1]: 2014-01-08 11:54:38 [2] [INFO] Listening at: http://0.0.0.0:34701 (2)
2014-01-08T11:54:38.879399+00:00 app[web.1]: 2014-01-08 11:54:38 [2] [INFO] Using worker: sync
2014-01-08T11:54:38.885898+00:00 app[web.1]: 2014-01-08 11:54:38 [7] [INFO] Booting worker with pid: 7
2014-01-08T11:54:39.099746+00:00 heroku[web.1]: State changed from starting to up
2014-01-08T11:54:39.829911+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-08T11:54:40.456129+00:00 heroku[worker.1]: State changed from starting to up
2014-01-08T11:54:40.774298+00:00 app[web.1]: cannot find gdoc name
2014-01-08T11:54:40.774298+00:00 app[web.1]: show entries
2014-01-08T11:54:40.774298+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T11:54:40.890708+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T11:54:40.890708+00:00 app[web.1]: get all combinations
2014-01-08T11:54:40.928228+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=828ms status=200 bytes=16659
2014-01-08T11:54:41.285241+00:00 app[worker.1]: 11:54:41 RQ worker started, version 0.3.13
2014-01-08T11:54:41.287479+00:00 app[worker.1]: 11:54:41 
2014-01-08T11:54:41.287539+00:00 app[worker.1]: 11:54:41 *** Listening on high, default, low...
2014-01-08T11:54:44.119199+00:00 heroku[router]: at=info method=GET path=/logout host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=23ms status=302 bytes=209
2014-01-08T11:54:44.207413+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=7ms service=9ms status=302 bytes=219
2014-01-08T11:54:47.932374+00:00 app[web.1]: running with user andygee@gmail.com 
2014-01-08T11:54:47.934852+00:00 heroku[router]: at=info method=POST path=/login host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=2ms service=12ms status=302 bytes=803
2014-01-08T11:54:49.121029+00:00 heroku[router]: at=info method=GET path=/auth_return?code=4/AVTGiLIvwyW9hAcRJ5ennFpD82to.ArXVpOySqiAemmS0T3UFEsPckGzjhgI host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=3ms service=888ms status=302 bytes=209
2014-01-08T11:54:49.198164+00:00 app[web.1]: cannot find gdoc name
2014-01-08T11:54:49.198164+00:00 app[web.1]: show entries
2014-01-08T11:54:49.198164+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T11:54:49.213969+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T11:54:49.213969+00:00 app[web.1]: get all combinations
2014-01-08T11:54:49.226029+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=0ms service=30ms status=200 bytes=16708
2014-01-08T11:54:50.795683+00:00 heroku[worker.2]: Starting process with command `python worker.py`
2014-01-08T11:54:51.385018+00:00 heroku[worker.2]: State changed from starting to up
2014-01-08T11:54:54.133355+00:00 app[worker.2]: 11:54:54 RQ worker started, version 0.3.13
2014-01-08T11:54:54.138438+00:00 app[worker.2]: 11:54:54 
2014-01-08T11:54:54.138438+00:00 app[worker.2]: 11:54:54 *** Listening on high, default, low...
2014-01-08T11:54:54.827106+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T11:54:54.836160+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T11:54:54.836160+00:00 app[web.1]: get all combinations
2014-01-08T11:54:54.845017+00:00 heroku[router]: at=info method=POST path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=5ms service=24ms status=200 bytes=16659
2014-01-08T11:55:01.750006+00:00 app[web.1]: running with user andygee@gmail.com 
2014-01-08T11:55:02.452791+00:00 app[web.1]: trying to find the spreadsheet named Quest Status 
2014-01-08T11:55:02.452844+00:00 app[web.1]: ['Quest Status']
2014-01-08T11:55:02.452927+00:00 app[web.1]: t0r5xf97B-k70k6TxherGcw
2014-01-08T11:55:02.853590+00:00 app[web.1]: running calc 70d855f3-be01-404e-b782-1295f3937bdc 
2014-01-08T11:55:02.853590+00:00 app[web.1]: Refreshing <Job 70d855f3-be01-404e-b782-1295f3937bdc: scheduler.run_scheduler_OAuth(<oauth2client.client.OAuth2Credentials object at 0x4868b90>, u'Quest Status')> 
2014-01-08T11:55:02.854566+00:00 app[web.1]: None
2014-01-08T11:55:02.855985+00:00 app[web.1]: 2014-01-08 11:55:02 [7] [ERROR] Error handling request
2014-01-08T11:55:02.855985+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T11:55:02.855985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-01-08T11:55:02.855985+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-01-08T11:55:02.855985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2014-01-08T11:55:02.855985+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2014-01-08T11:55:02.855985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2014-01-08T11:55:02.855985+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-01-08T11:55:02.855985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-01-08T11:55:02.855985+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-01-08T11:55:02.856167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-01-08T11:55:02.856167+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-01-08T11:55:02.856167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-01-08T11:55:02.856167+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-01-08T11:55:02.856167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-01-08T11:55:02.856167+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-01-08T11:55:02.856167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-01-08T11:55:02.856167+00:00 app[web.1]:     rv = self.dispatch_request()
2014-01-08T11:55:02.856167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-01-08T11:55:02.856167+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-01-08T11:55:02.856337+00:00 app[web.1]:   File "/app/rosterrun.py", line 141, in show_entries
2014-01-08T11:55:02.856337+00:00 app[web.1]:     run_calculation()
2014-01-08T11:55:02.856337+00:00 app[web.1]:   File "/app/rosterrun.py", line 273, in run_calculation
2014-01-08T11:55:02.856337+00:00 app[web.1]:     checkCalculation()
2014-01-08T11:55:02.856337+00:00 app[web.1]:   File "/app/rosterrun.py", line 292, in checkCalculation
2014-01-08T11:55:02.856337+00:00 app[web.1]:     for i in range(0, len(parties) - 1):
2014-01-08T11:55:02.856337+00:00 app[web.1]: TypeError: object of type 'NoneType' has no len()
2014-01-08T11:55:02.855816+00:00 heroku[router]: at=info method=POST path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=1115ms status=500 bytes=135
2014-01-08T11:55:02.944738+00:00 app[worker.1]: 11:55:02 default: scheduler.run_scheduler_OAuth(<oauth2client.client.OAuth2Credentials object at 0x4868b90>, u'Quest Status') (70d855f3-be01-404e-b782-1295f3937bdc)
2014-01-08T11:55:04.230361+00:00 app[worker.1]: trying to find the spreadsheet named Quest Status 
2014-01-08T11:55:04.230361+00:00 app[worker.1]: ['Quest Status']
2014-01-08T11:55:04.230361+00:00 app[worker.1]: t0r5xf97B-k70k6TxherGcw
2014-01-08T11:54:44.296990+00:00 heroku[router]: at=info method=GET path=/login host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=2ms service=8ms status=200 bytes=563
Terminate batch job (Y/N)? 
