2014-01-08T08:12:20.567570+00:00 heroku[worker.2]: Process exited with status 0
2014-01-08T08:12:21.017271+00:00 heroku[worker.1]: Process exited with status 0
2014-01-08T08:12:21.302016+00:00 heroku[web.1]: Process exited with status 0
2014-01-08T08:12:24.600138+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-08T08:12:25.209081+00:00 heroku[worker.1]: State changed from starting to up
2014-01-08T08:12:25.602301+00:00 app[worker.1]: 08:12:25 *** Listening on high, default, low...
2014-01-08T08:12:25.600037+00:00 app[worker.1]: 08:12:25 RQ worker started, version 0.3.13
2014-01-08T08:12:25.602237+00:00 app[worker.1]: 08:12:25 
2014-01-08T08:12:26.931970+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2014-01-08T08:12:27.989135+00:00 app[web.1]: 2014-01-08 08:12:27 [2] [INFO] Starting gunicorn 18.0
2014-01-08T08:12:27.989753+00:00 app[web.1]: 2014-01-08 08:12:27 [2] [INFO] Listening at: http://0.0.0.0:47158 (2)
2014-01-08T08:12:27.989880+00:00 app[web.1]: 2014-01-08 08:12:27 [2] [INFO] Using worker: sync
2014-01-08T08:12:27.997490+00:00 app[web.1]: 2014-01-08 08:12:27 [7] [INFO] Booting worker with pid: 7
2014-01-08T08:12:28.008270+00:00 app[web.1]: 2014-01-08 08:12:28 [7] [ERROR] Exception in worker process:
2014-01-08T08:12:28.008270+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T08:12:28.008270+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T08:12:28.008270+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T08:12:28.008270+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T08:12:28.008270+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T08:12:28.008270+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T08:12:28.008270+00:00 app[web.1]:     worker.init_process()
2014-01-08T08:12:28.008270+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T08:12:28.008514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T08:12:28.008514+00:00 app[web.1]:     parties = q.enqueue(func=run_scheduler_OAuth, credentials, session['doc'])
2014-01-08T08:12:28.008270+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T08:12:28.008514+00:00 app[web.1]:   File "/app/rosterrun.py", line 266
2014-01-08T08:12:28.008514+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T08:12:28.008514+00:00 app[web.1]:     __import__(module)
2014-01-08T08:12:28.008514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T08:12:28.008514+00:00 app[web.1]: SyntaxError: non-keyword arg after keyword arg
2014-01-08T08:12:28.008514+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T08:12:28.008514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T08:12:28.008514+00:00 app[web.1]:     worker.init_process()
2014-01-08T08:12:28.008686+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T08:12:28.008686+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T08:12:28.008686+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T08:12:28.008686+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T08:12:28.008686+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T08:12:28.008686+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T08:12:28.008686+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T08:12:28.008686+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T08:12:28.008686+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T08:12:28.008686+00:00 app[web.1]:     __import__(module)
2014-01-08T08:12:28.009163+00:00 app[web.1]: SyntaxError: non-keyword arg after keyword arg
2014-01-08T08:12:28.009163+00:00 app[web.1]:   File "/app/rosterrun.py", line 266
2014-01-08T08:12:28.009163+00:00 app[web.1]:     parties = q.enqueue(func=run_scheduler_OAuth, credentials, session['doc'])
2014-01-08T08:12:28.009163+00:00 app[web.1]: 2014-01-08 08:12:28 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T08:12:28.132040+00:00 app[web.1]: 2014-01-08 08:12:28 [2] [INFO] Shutting down: Master
2014-01-08T08:12:28.132040+00:00 app[web.1]: 2014-01-08 08:12:28 [2] [INFO] Reason: Worker failed to boot.
2014-01-08T08:12:29.350058+00:00 heroku[web.1]: Process exited with status 3
2014-01-08T08:12:29.364959+00:00 heroku[web.1]: State changed from starting to crashed
2014-01-08T08:12:29.365742+00:00 heroku[web.1]: State changed from crashed to starting
2014-01-08T08:12:31.807438+00:00 heroku[worker.2]: Starting process with command `python worker.py`
2014-01-08T08:12:32.459253+00:00 heroku[worker.2]: State changed from starting to up
2014-01-08T08:12:33.322692+00:00 app[worker.2]: 08:12:33 *** Listening on high, default, low...
2014-01-08T08:12:33.320856+00:00 app[worker.2]: 08:12:33 RQ worker started, version 0.3.13
2014-01-08T08:12:33.322588+00:00 app[worker.2]: 08:12:33 
2014-01-08T08:12:41.816797+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2014-01-08T08:12:42.918956+00:00 app[web.1]: 2014-01-08 08:12:42 [2] [INFO] Listening at: http://0.0.0.0:35174 (2)
2014-01-08T08:12:42.919071+00:00 app[web.1]: 2014-01-08 08:12:42 [2] [INFO] Using worker: sync
2014-01-08T08:12:42.917912+00:00 app[web.1]: 2014-01-08 08:12:42 [2] [INFO] Starting gunicorn 18.0
2014-01-08T08:12:42.927200+00:00 app[web.1]: 2014-01-08 08:12:42 [7] [INFO] Booting worker with pid: 7
2014-01-08T08:12:42.936589+00:00 app[web.1]: 2014-01-08 08:12:42 [7] [ERROR] Exception in worker process:
2014-01-08T08:12:42.936589+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T08:12:42.936589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T08:12:42.936589+00:00 app[web.1]:     worker.init_process()
2014-01-08T08:12:42.936589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T08:12:42.936589+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T08:12:42.936806+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T08:12:42.936806+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T08:12:42.936589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T08:12:42.936589+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T08:12:42.936589+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T08:12:42.936589+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T08:12:42.936806+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T08:12:42.936806+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T08:12:42.936806+00:00 app[web.1]:     worker.init_process()
2014-01-08T08:12:42.936967+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T08:12:42.936967+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T08:12:42.936967+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T08:12:42.936967+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T08:12:42.936806+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T08:12:42.936806+00:00 app[web.1]:     __import__(module)
2014-01-08T08:12:42.936806+00:00 app[web.1]:   File "/app/rosterrun.py", line 266
2014-01-08T08:12:42.936806+00:00 app[web.1]:     parties = q.enqueue(func=run_scheduler_OAuth, credentials,
 session['doc'])
2014-01-08T08:12:42.936806+00:00 app[web.1]: SyntaxError: non-keyword arg after keyword arg
2014-01-08T08:12:42.936967+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T08:12:42.936967+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T08:12:42.936967+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T08:12:42.936967+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T08:12:42.936967+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T08:12:42.936967+00:00 app[web.1]:     __import__(module)
2014-01-08T08:12:42.937489+00:00 app[web.1]:   File "/app/rosterrun.py", line 266
2014-01-08T08:12:42.937489+00:00 app[web.1]:     parties = q.enqueue(func=run_scheduler_OAuth, credentials, session['doc'])
2014-01-08T08:12:42.937489+00:00 app[web.1]: SyntaxError: non-keyword arg after keyword arg
2014-01-08T08:12:42.937489+00:00 app[web.1]: 2014-01-08 08:12:42 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T08:12:43.057940+00:00 app[web.1]: 2014-01-08 08:12:43 [2] [INFO] Shutting down: Master
2014-01-08T08:12:43.057940+00:00 app[web.1]: 2014-01-08 08:12:43 [2] [INFO] Reason: Worker failed to boot.
2014-01-08T08:12:44.237894+00:00 heroku[web.1]: Process exited with status 3
2014-01-08T08:12:44.251601+00:00 heroku[web.1]: State changed from starting to crashed
2014-01-08T08:12:46.069498+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno= connect= service= status=503 bytes=
Terminate batch job (Y/N)? 
