2014-01-08T23:11:50.421883+00:00 app[web.1]: 2014-01-08 23:11:50 [2] [INFO] Listening at: http://0.0.0.0:8618 (2)
2014-01-08T23:11:50.421951+00:00 app[web.1]: 2014-01-08 23:11:50 [2] [INFO] Using worker: sync
2014-01-08T23:11:50.428953+00:00 app[web.1]: 2014-01-08 23:11:50 [7] [INFO] Booting worker with pid: 7
2014-01-08T23:11:50.598108+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T23:11:50.598108+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T23:11:50.598108+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T23:11:50.598108+00:00 app[web.1]: 2014-01-08 23:11:50 [7] [ERROR] Exception in worker process:
2014-01-08T23:11:50.598108+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T23:11:50.598108+00:00 app[web.1]:     worker.init_process()
2014-01-08T23:11:50.598108+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T23:11:50.598108+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T23:11:50.598302+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T23:11:50.598108+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T23:11:50.598108+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T23:11:50.598302+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T23:11:50.598302+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T23:11:50.598302+00:00 app[web.1]:     __import__(module)
2014-01-08T23:11:50.598302+00:00 app[web.1]:   File "/app/rosterrun.py", line 3, in <module>
2014-01-08T23:11:50.598302+00:00 app[web.1]:   File "/app/worker.py", line 6, in <module>
2014-01-08T23:11:50.598302+00:00 app[web.1]:     from worker import conn
2014-01-08T23:11:50.598302+00:00 app[web.1]:     from worker import conn
2014-01-08T23:11:50.598302+00:00 app[web.1]: ImportError: cannot import name conn
2014-01-08T23:11:50.598302+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T23:11:50.598459+00:00 app[web.1]:     worker.init_process()
2014-01-08T23:11:50.598459+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T23:11:50.598459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T23:11:50.598459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T23:11:50.598459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T23:11:50.598459+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T23:11:50.598459+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T23:11:50.598459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T23:11:50.598459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T23:11:50.598848+00:00 app[web.1]:     __import__(module)
2014-01-08T23:11:50.598459+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T23:11:50.598848+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T23:11:50.598848+00:00 app[web.1]:   File "/app/rosterrun.py", line 3, in <module>
2014-01-08T23:11:50.598848+00:00 app[web.1]:     from worker import conn
2014-01-08T23:11:50.598848+00:00 app[web.1]:   File "/app/worker.py", line 6, in <module>
2014-01-08T23:11:50.598848+00:00 app[web.1]:     from worker import conn
2014-01-08T23:11:50.598848+00:00 app[web.1]: ImportError: cannot import name conn
2014-01-08T23:11:50.598848+00:00 app[web.1]: 2014-01-08 23:11:50 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T23:11:50.723173+00:00 app[web.1]: 2014-01-08 23:11:50 [2] [INFO] Reason: Worker failed to boot.
2014-01-08T23:11:50.723173+00:00 app[web.1]: 2014-01-08 23:11:50 [2] [INFO] Shutting down: Master
2014-01-08T23:11:52.090602+00:00 heroku[web.1]: Process exited with status 3
2014-01-08T23:11:52.126402+00:00 heroku[web.1]: State changed from starting to crashed
2014-01-08T23:29:41.488640+00:00 heroku[worker.2]: State changed from crashed to starting
2014-01-08T23:29:54.169516+00:00 heroku[worker.2]: Starting process with command `python worker.py`
2014-01-08T23:29:54.761494+00:00 heroku[worker.2]: State changed from starting to up
2014-01-08T23:29:55.322963+00:00 app[worker.2]:     from worker import conn
2014-01-08T23:29:55.322963+00:00 app[worker.2]: Traceback (most recent call last):
2014-01-08T23:29:55.322963+00:00 app[worker.2]:   File "/app/worker.py", line 6, in <module>
2014-01-08T23:29:55.322963+00:00 app[worker.2]:   File "worker.py", line 6, in <module>
2014-01-08T23:29:55.322963+00:00 app[worker.2]: ImportError: cannot import name conn
2014-01-08T23:29:55.322963+00:00 app[worker.2]:     from worker import conn
2014-01-08T23:29:56.730742+00:00 heroku[worker.2]: Process exited with status 1
2014-01-08T23:29:56.740737+00:00 heroku[worker.2]: State changed from up to crashed
2014-01-09T00:12:41.144671+00:00 heroku[worker.2]: State changed from crashed to starting
2014-01-09T00:12:55.626173+00:00 heroku[worker.2]: State changed from starting to up
2014-01-09T00:12:58.189350+00:00 heroku[worker.2]: State changed from up to crashed
2014-01-09T00:12:54.977319+00:00 heroku[worker.2]: Starting process with command `python worker.py`
2014-01-09T00:12:56.783114+00:00 app[worker.2]: Traceback (most recent call last):
2014-01-09T00:12:56.783114+00:00 app[worker.2]:   File "worker.py", line 6, in <module>
2014-01-09T00:12:56.783114+00:00 app[worker.2]:     from worker import conn
2014-01-09T00:12:56.783114+00:00 app[worker.2]:   File "/app/worker.py", line 6, in <module>
2014-01-09T00:12:56.783114+00:00 app[worker.2]:     from worker import conn
2014-01-09T00:12:56.783114+00:00 app[worker.2]: ImportError: cannot import name conn
2014-01-09T00:12:58.165585+00:00 heroku[worker.2]: Process exited with status 1
2014-01-09T00:14:43.158944+00:00 heroku[worker.1]: State changed from crashed to starting
2014-01-09T00:14:55.754442+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-09T00:14:56.418300+00:00 heroku[worker.1]: State changed from starting to up
2014-01-09T00:14:57.000492+00:00 app[worker.1]:     from worker import conn
2014-01-09T00:14:57.000492+00:00 app[worker.1]:     from worker import conn
2014-01-09T00:14:57.000492+00:00 app[worker.1]: ImportError: cannot import name conn
2014-01-09T00:14:57.000492+00:00 app[worker.1]: Traceback (most recent call last):
2014-01-09T00:14:57.000492+00:00 app[worker.1]:   File "worker.py", line 6, in <module>
2014-01-09T00:14:57.000492+00:00 app[worker.1]:   File "/app/worker.py", line 6, in <module>
2014-01-09T00:14:58.167035+00:00 heroku[worker.1]: Process exited with status 1
2014-01-09T00:14:58.166990+00:00 heroku[worker.1]: State changed from up to crashed
2014-01-09T00:32:51.010880+00:00 heroku[worker.1]: State changed from crashed to starting
2014-01-09T00:33:05.943091+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-09T00:33:06.615705+00:00 heroku[worker.1]: State changed from starting to up
2014-01-09T00:33:07.321081+00:00 app[worker.1]:   File "/app/worker.py", line 6, in <module>
2014-01-09T00:33:07.321081+00:00 app[worker.1]:     from worker import conn
2014-01-09T00:33:07.321081+00:00 app[worker.1]: ImportError: cannot import name conn
2014-01-09T00:33:07.321081+00:00 app[worker.1]: Traceback (most recent call last):
2014-01-09T00:33:07.321081+00:00 app[worker.1]:   File "worker.py", line 6, in <module>
2014-01-09T00:33:07.321081+00:00 app[worker.1]:     from worker import conn
2014-01-09T00:33:08.571261+00:00 heroku[worker.1]: Process exited with status 1
2014-01-09T00:33:08.614420+00:00 heroku[worker.1]: State changed from up to crashed
2014-01-09T00:44:34.830882+00:00 heroku[worker.2]: State changed from crashed to starting
2014-01-09T00:44:47.145924+00:00 heroku[worker.2]: Starting process with command `python worker.py`
2014-01-09T00:44:47.909178+00:00 heroku[worker.2]: State changed from starting to up
2014-01-09T00:44:48.441980+00:00 app[worker.2]: Traceback (most recent call last):
2014-01-09T00:44:48.441980+00:00 app[worker.2]:   File "worker.py", line 6, in <module>
2014-01-09T00:44:48.441980+00:00 app[worker.2]:     from worker import conn
2014-01-09T00:44:48.441980+00:00 app[worker.2]:   File "/app/worker.py", line 6, in <module>
2014-01-09T00:44:48.441980+00:00 app[worker.2]:     from worker import conn
2014-01-09T00:44:48.441980+00:00 app[worker.2]: ImportError: cannot import name conn
2014-01-09T00:44:49.560585+00:00 heroku[worker.2]: Process exited with status 1
2014-01-09T00:44:49.567447+00:00 heroku[worker.2]: State changed from up to crashed
2014-01-09T00:56:42.066561+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno= connect= service= status=503 bytes=
2014-01-09T00:57:38.784572+00:00 heroku[worker.1]: State changed from crashed to starting
2014-01-09T00:57:49.050145+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-09T00:57:49.627243+00:00 heroku[worker.1]: State changed from starting to up
2014-01-09T00:57:50.048503+00:00 app[worker.1]: Traceback (most recent call last):
2014-01-09T00:57:50.048503+00:00 app[worker.1]:   File "worker.py", line 6, in <module>
2014-01-09T00:57:50.048503+00:00 app[worker.1]:     from worker import conn
2014-01-09T00:57:50.048503+00:00 app[worker.1]:   File "/app/worker.py", line 6, in <module>
2014-01-09T00:57:50.048503+00:00 app[worker.1]:     from worker import conn
2014-01-09T00:57:50.048503+00:00 app[worker.1]: ImportError: cannot import name conn
2014-01-09T00:57:51.140520+00:00 heroku[worker.1]: Process exited with status 1
2014-01-09T00:57:51.152066+00:00 heroku[worker.1]: State changed from up to crashed
2014-01-09T01:13:44.902074+00:00 heroku[worker.1]: State changed from crashed to starting
2014-01-09T01:13:56.817839+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-09T01:13:58.267906+00:00 app[worker.1]: Traceback (most recent call last):
2014-01-09T01:13:58.267906+00:00 app[worker.1]:   File "worker.py", line 6, in <module>
2014-01-09T01:13:58.267906+00:00 app[worker.1]:     from worker import conn
2014-01-09T01:13:58.267906+00:00 app[worker.1]:   File "/app/worker.py", line 6, in <module>
2014-01-09T01:13:58.267906+00:00 app[worker.1]:     from worker import conn
2014-01-09T01:13:58.267906+00:00 app[worker.1]: ImportError: cannot import name conn
2014-01-09T01:13:59.827959+00:00 heroku[worker.1]: Process exited with status 1
2014-01-09T01:13:59.847077+00:00 heroku[worker.1]: State changed from up to crashed
2014-01-09T01:13:57.507933+00:00 heroku[worker.1]: State changed from starting to up
2014-01-09T01:30:55.850293+00:00 heroku[worker.1]: State changed from crashed to starting
2014-01-09T01:31:07.164332+00:00 heroku[worker.1]: Starting process with command `python worker.py`
2014-01-09T01:31:07.705264+00:00 heroku[worker.1]: State changed from starting to up
2014-01-09T01:31:08.409972+00:00 app[worker.1]: Traceback (most recent call last):
2014-01-09T01:31:08.409972+00:00 app[worker.1]:   File "worker.py", line 6, in <module>
2014-01-09T01:31:08.409972+00:00 app[worker.1]:     from worker import conn
2014-01-09T01:31:08.409972+00:00 app[worker.1]:   File "/app/worker.py", line 6, in <module>
2014-01-09T01:31:08.409972+00:00 app[worker.1]:     from worker import conn
2014-01-09T01:31:08.409972+00:00 app[worker.1]: ImportError: cannot import name conn
2014-01-09T01:31:09.748786+00:00 heroku[worker.1]: Process exited with status 1
2014-01-09T01:31:09.765088+00:00 heroku[worker.1]: State changed from up to crashed
Terminate batch job (Y/N)? 
